import { PrismaClient } from '@prisma/client';
import { CommonStatus } from '../../src/shared/constants/common-status.constant';

const prisma = new PrismaClient();

export async function seedConfigs() {
  console.log('🌱 开始创建可配置数据...');

  const configsData = [
    // ====================== 系统配置 ======================
    {
      key: 'system.name',
      value: 'GVRAY Admin',
      name: '系统名称',
      description: '系统显示名称，影响页面标题和邮件签名',
      type: 'string',
      group: 'system',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: '品牌基础配置',
    },
    {
      key: 'system.logo',
      value: '/logo.svg',
      name: '系统 Logo',
      description: '顶部导航栏及登录页 Logo 地址',
      type: 'string',
      group: 'system',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: '品牌视觉配置',
    },
    {
      key: 'system.favicon',
      value: '/favicon.ico',
      name: '浏览器图标',
      description: '浏览器标签页 Favicon 地址',
      type: 'string',
      group: 'system',
      status: CommonStatus.ENABLED,
      sort: 2,
      remark: '品牌视觉配置',
    },
    {
      key: 'system.welcomeMessage',
      value: '欢迎使用 GVRAY Admin',
      name: '系统欢迎语',
      description: '登录成功后首页展示的欢迎文案',
      type: 'string',
      group: 'system',
      status: CommonStatus.ENABLED,
      sort: 3,
      remark: '品牌文案配置',
    },
    {
      key: 'system.copyright',
      value: '© 2025 GVRAY Admin. All rights reserved.',
      name: '版权信息',
      description: '页脚版权文案',
      type: 'string',
      group: 'system',
      status: CommonStatus.ENABLED,
      sort: 4,
      remark: '法律信息配置',
    },
    {
      key: 'system.icp',
      value: '',
      name: 'ICP 备案号',
      description: '中国大陆网站备案号，显示在页脚',
      type: 'string',
      group: 'system',
      status: CommonStatus.ENABLED,
      sort: 5,
      remark: '法律信息配置',
    },
    {
      key: 'system.timezone',
      value: 'Asia/Shanghai',
      name: '默认时区',
      description: '系统默认时区，影响服务端时间计算及前端默认展示',
      type: 'string',
      group: 'system',
      status: CommonStatus.ENABLED,
      sort: 6,
      remark: '区域化配置',
    },

    // ====================== 安全配置 ======================
    {
      key: 'security.watermarkEnabled',
      value: 'true',
      name: '全局水印',
      description: '开启后所有页面显示当前用户名水印，防止截图泄密',
      type: 'boolean',
      group: 'security',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: '数据防泄漏',
    },
    {
      key: 'security.passwordMinLength',
      value: '8',
      name: '密码最小长度',
      description: '用户密码最小字符数，建议 ≥ 8',
      type: 'number',
      group: 'security',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: '密码策略',
    },
    {
      key: 'security.passwordMaxLength',
      value: '32',
      name: '密码最大长度',
      description: '用户密码最大字符数，防止 DoS',
      type: 'number',
      group: 'security',
      status: CommonStatus.ENABLED,
      sort: 2,
      remark: '密码策略',
    },
    {
      key: 'security.passwordRequireComplexity',
      value: 'true',
      name: '密码复杂度要求',
      description: '要求密码必须包含大小写字母、数字及特殊字符中的至少两种',
      type: 'boolean',
      group: 'security',
      status: CommonStatus.ENABLED,
      sort: 3,
      remark: '密码策略',
    },
    {
      key: 'security.passwordExpiryDays',
      value: '0',
      name: '密码有效期(天)',
      description: '密码强制重置周期，0 表示永不过期（符合 NIST 建议）',
      type: 'number',
      group: 'security',
      status: CommonStatus.ENABLED,
      sort: 4,
      remark: '密码策略',
    },
    {
      key: 'security.mustChangePassword',
      value: 'true',
      name: '首次登录强制改密',
      description: '新用户或重置密码后首次登录必须修改密码',
      type: 'boolean',
      group: 'security',
      status: CommonStatus.ENABLED,
      sort: 5,
      remark: '账号安全',
    },
    {
      key: 'security.loginFailureLockCount',
      value: '5',
      name: '登录失败锁定次数',
      description: '连续登录失败达到该次数后锁定账号',
      type: 'number',
      group: 'security',
      status: CommonStatus.ENABLED,
      sort: 6,
      remark: '暴力破解防护',
    },
    {
      key: 'security.loginFailureLockDuration',
      value: '30',
      name: '账号锁定时长(分钟)',
      description: '登录失败锁定后自动解锁的时间',
      type: 'number',
      group: 'security',
      status: CommonStatus.ENABLED,
      sort: 7,
      remark: '暴力破解防护',
    },
    {
      key: 'security.sessionConcurrentLimit',
      value: '3',
      name: '单用户最大会话数',
      description: '同一账号同时在线的最大设备数，超出后最早的会话将被踢出',
      type: 'number',
      group: 'security',
      status: CommonStatus.ENABLED,
      sort: 8,
      remark: '会话管理',
    },

    // ====================== 用户配置 ======================
    {
      key: 'user.defaultRole',
      value: 'user',
      name: '默认角色编码',
      description: '新注册用户或被管理员创建用户时分配的默认角色',
      type: 'string',
      group: 'user',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: '用户初始化',
    },
    {
      key: 'user.defaultAvatar',
      value: 'https://api.dicebear.com/9.x/bottts/svg?seed=GVRAY',
      name: '默认头像地址',
      description: '用户未上传头像时的默认头像 URL',
      type: 'string',
      group: 'user',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: '用户初始化',
    },

    // ====================== 界面配置 ======================
    {
      key: 'ui.theme',
      value: 'light',
      name: '默认主题',
      description: '系统默认主题，用户可在个人设置中覆盖',
      type: 'string',
      group: 'ui',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: '界面主题',
    },
    {
      key: 'ui.language',
      value: 'zh-CN',
      name: '默认语言',
      description: '系统默认语言，影响日期/数字/文案展示',
      type: 'string',
      group: 'ui',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: '国际化',
    },
    {
      key: 'ui.pageSize',
      value: '10',
      name: '表格默认分页',
      description: '数据列表每页默认展示条数',
      type: 'number',
      group: 'ui',
      status: CommonStatus.ENABLED,
      sort: 2,
      remark: '界面偏好',
    },
    {
      key: 'ui.showBreadcrumb',
      value: 'true',
      name: '显示面包屑',
      description: '页面顶部是否展示面包屑导航',
      type: 'boolean',
      group: 'ui',
      status: CommonStatus.ENABLED,
      sort: 3,
      remark: '界面布局',
    },
    {
      key: 'ui.sidebarCollapsed',
      value: 'false',
      name: '侧边栏默认折叠',
      description: '登录后侧边栏是否默认收起',
      type: 'boolean',
      group: 'ui',
      status: CommonStatus.ENABLED,
      sort: 4,
      remark: '界面布局',
    },
    {
      key: 'ui.dateFormat',
      value: 'YYYY-MM-DD',
      name: '日期格式',
      description: '系统全局日期展示格式',
      type: 'string',
      group: 'ui',
      status: CommonStatus.ENABLED,
      sort: 5,
      remark: '区域化',
    },
    {
      key: 'ui.timeFormat',
      value: 'HH:mm:ss',
      name: '时间格式',
      description: '系统全局时间展示格式（24小时制）',
      type: 'string',
      group: 'ui',
      status: CommonStatus.ENABLED,
      sort: 6,
      remark: '区域化',
    },

    // ====================== 功能开关 ======================
    {
      key: 'feature.register',
      value: 'true',
      name: '开放注册',
      description: '是否允许前端自助注册账号',
      type: 'boolean',
      group: 'feature',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: '准入控制',
    },
    {
      key: 'feature.auditLog',
      value: 'true',
      name: '操作审计日志',
      description: '是否记录并展示用户操作审计日志',
      type: 'boolean',
      group: 'feature',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: '安全审计',
    },
    {
      key: 'feature.emailNotification',
      value: 'true',
      name: '邮件通知',
      description: '是否允许系统发送邮件通知（依赖邮件配置）',
      type: 'boolean',
      group: 'feature',
      status: CommonStatus.ENABLED,
      sort: 2,
      remark: '通知通道',
    },
    {
      key: 'feature.smsNotification',
      value: 'false',
      name: '短信通知',
      description: '是否允许系统发送短信通知（依赖短信配置）',
      type: 'boolean',
      group: 'feature',
      status: CommonStatus.ENABLED,
      sort: 3,
      remark: '通知通道',
    },
    {
      key: 'feature.mfa',
      value: 'false',
      name: '双因子认证(MFA)',
      description: '是否启用 TOTP 双因子认证功能',
      type: 'boolean',
      group: 'feature',
      status: CommonStatus.ENABLED,
      sort: 4,
      remark: '身份安全',
    },

    // ====================== 存储配置 ======================
    {
      key: 'storage.provider',
      value: 'local',
      name: '存储驱动',
      description: '文件上传存储后端：local / oss / cos / minio / s3',
      type: 'string',
      group: 'storage',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: '存储后端',
    },
    {
      key: 'storage.maxFileSize',
      value: '10485760',
      name: '最大上传大小(字节)',
      description: '单个文件上传大小上限，单位字节（默认 10MB）',
      type: 'number',
      group: 'storage',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: '上传限制',
    },
    {
      key: 'storage.allowedTypes',
      value: 'jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx',
      name: '允许上传的文件类型',
      description: '允许上传的文件扩展名列表，逗号分隔',
      type: 'string',
      group: 'storage',
      status: CommonStatus.ENABLED,
      sort: 2,
      remark: '上传限制',
    },
    {
      key: 'storage.baseUrl',
      value: '',
      name: '文件访问基础 URL',
      description: '文件下载/预览地址前缀，为空则使用相对路径',
      type: 'string',
      group: 'storage',
      status: CommonStatus.ENABLED,
      sort: 3,
      remark: '访问配置',
    },

    // ====================== 第三方登录 ======================
    {
      key: 'oauth.githubEnabled',
      value: 'false',
      name: 'GitHub 登录',
      description: '是否启用 GitHub OAuth 登录',
      type: 'boolean',
      group: 'oauth',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: 'OAuth 开关',
    },
    {
      key: 'oauth.googleEnabled',
      value: 'false',
      name: 'Google 登录',
      description: '是否启用 Google OAuth 登录',
      type: 'boolean',
      group: 'oauth',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: 'OAuth 开关',
    },
    {
      key: 'oauth.wechatEnabled',
      value: 'false',
      name: '微信登录',
      description: '是否启用微信开放平台扫码登录',
      type: 'boolean',
      group: 'oauth',
      status: CommonStatus.ENABLED,
      sort: 2,
      remark: 'OAuth 开关',
    },

    // ====================== 邮件配置 ======================
    {
      key: 'mail.enabled',
      value: 'false',
      name: '邮件功能开关',
      description: '是否启用 SMTP 邮件发送功能',
      type: 'boolean',
      group: 'mail',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: '邮件总开关',
    },
    {
      key: 'mail.host',
      value: '',
      name: 'SMTP 主机',
      description: 'SMTP 服务器地址，如 smtp.qq.com',
      type: 'string',
      group: 'mail',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: 'SMTP 连接',
    },
    {
      key: 'mail.port',
      value: '465',
      name: 'SMTP 端口',
      description: 'SMTP 服务器端口，常用 465(SSL) 或 587(TLS)',
      type: 'number',
      group: 'mail',
      status: CommonStatus.ENABLED,
      sort: 2,
      remark: 'SMTP 连接',
    },
    {
      key: 'mail.from',
      value: '',
      name: '发件人地址',
      description: '邮件发送方显示地址，如 noreply@gvray.com',
      type: 'string',
      group: 'mail',
      status: CommonStatus.ENABLED,
      sort: 3,
      remark: '邮件发送方',
    },
    {
      key: 'mail.ssl',
      value: 'true',
      name: 'SSL/TLS 加密',
      description: '是否使用 SSL/TLS 加密连接',
      type: 'boolean',
      group: 'mail',
      status: CommonStatus.ENABLED,
      sort: 4,
      remark: 'SMTP 安全',
    },

    // ====================== 短信配置 ======================
    {
      key: 'sms.enabled',
      value: 'false',
      name: '短信功能开关',
      description: '是否启用短信发送功能',
      type: 'boolean',
      group: 'sms',
      status: CommonStatus.ENABLED,
      sort: 0,
      remark: '短信总开关',
    },
    {
      key: 'sms.provider',
      value: 'aliyun',
      name: '短信服务商',
      description: '短信服务提供商：aliyun / tencent / huawei / yunpian',
      type: 'string',
      group: 'sms',
      status: CommonStatus.ENABLED,
      sort: 1,
      remark: '服务商选择',
    },
    {
      key: 'sms.signature',
      value: '',
      name: '短信签名',
      description: '短信模板签名，如【GVRAY】',
      type: 'string',
      group: 'sms',
      status: CommonStatus.ENABLED,
      sort: 2,
      remark: '短信内容',
    },
  ];

  for (const configData of configsData) {
    await prisma.config.upsert({
      where: { key: configData.key },
      update: configData,
      create: configData,
    });
  }

  console.log(`✅ 配置数据创建完成，共 ${configsData.length} 项`);
}
